# GENERAL PARAMETERS=
# Path where data is recorded
savePath: "/home/sthithpragya/Study/Thesis/data_for_learning/recorded_data/misc5"
#------------------------------------------

# ROS PARAMETERS
# Topic to send command to manipulator
publishToRobot: "/iiwa/PositionController/command" # type -> std_msgs::Float64MultiArray

# Sensor readings from the manipulator
robotJointState: "/iiwa/joint_states" # type -> sensor_msgs::JointState

# NOTE: If the desired message types for these topics differ, 
# manually change the message type in the source files (mention location)

pubFreq: 200
#------------------------------------------

# ROBOT PARAMETERS

totalJoints: 7

qLimUpper:
  - 2.7925 
  - 1.2217
  - 2.7925
  - 1.9198
  - 2.7925
  - 1.9198
  - 2.8797

qLimLower:
  - -2.7925 
  - -1.2217
  - -2.7925
  - -1.9198
  - -2.7925
  - -1.9198
  - -2.8797

qDotLimUpper:
  - 1.4835
  - 1.4835
  - 1.7453
  - 1.3089
  - 2.2689
  - 2.3561
  - 2.3561

qDotLimLower:
  - -1.4835
  - -1.4835
  - -1.7453
  - -1.3089
  - -2.2689
  - -2.3561
  - -2.3561

# qLimUpper:
#   - 1.5 
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5

# qLimLower:
#   - -1.5 
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5

# qDotLimUpper:
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5
#   - 1.5

# qDotLimLower:
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#   - -1.5
#------------------------------------------

# PolarDS PARAMETERS
dT: 0.005
alpha: 1.0
beta: 0.5
randPointCount: 50 # a choice of number of random points during optimization
increm: 0.1
angleDispLimit: 7.85 # 2.5 M_PI
rLim:
  - 0.25
  - 1
#------------------------------------------

# TRAJECTORY PARAMETERS
looping: "open" 
# looping: "closed"

# open    - DS uses the desired joint position and velocity (as computed by the DS) to compute the subsequent trajectory
# closed  - DS uses the actual joint position and velocity to compute the subsequent phase space trajectory

#Initial manipulator configuration (before starting data collection)
qStart: 
  - -0.2
  - 1.0
  - 0.2
  - -1.2
  - 1.0
  - 0.8
  - 0.1

qDotStart:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0

