## FILE LOCATIONS
savePath: "/home/lasa/sthith/InvDyn_Learning/recorded_data/results_dynamic" # location of whichever data that is to be processed

#-----------------------------------------------

## PARAMETERS ASSOCIATED WITH DATA SUB-ASMPLING
trainSize: 0
testSize: 40000

# Filtering the recorded data
toFilterQ: False
toFilterQDot: False
toFilterTau: False

# To filter, we are using the Moving Average filter. Specify the size of the window of the Moving Average filter
qFilterVal: 41
qDotFilterVal: 41
tauFilterVal: 41

recordingResultantTorque: True 
# True - The torque-sensor senses the resultant torque (i.e. the applied torque was -(recorded value))
# False - Otherwise

dt: 0.005 # Inverse of publishing frequency

useArtVel: False # set to True incase the robot (or simulator) is giving incorrect or no joint velocities. NOTE: These velocities are not filtered initially.

# For making the grid in each joint's phase space
qBound: 0.3
qDotBound: 0.3

useForTesting: True # Whether to normalise data or not
# For learning purposes, False
# For testing with some other learned model, True
# When True:
#           > does not normalise the data
#           > does not prepare train sets
#           > Does not prepare sparse data sets for nuSVR
#           > Only prepares non-normalised test sets
#-----------------------------------------------
# testMode: "static" ## Relevant iff useForTesting is True
testMode: "dynamic"

## PARAMETERS ASSOCIATED WITH ROBOT

# joint count
totalJoints: 7

# Joint angle limits
qLimUpper:
  - 2.7925 
  - 1.2217
  - 2.7925
  - 1.9198
  - 2.7925
  - 1.9198
  - 2.8797

qLimLower:
  - -2.7925 
  - -1.2217
  - -2.7925
  - -1.9198
  - -2.7925
  - -1.9198
  - -2.8797

# Joint velocity limits
qDotLimUpper:
  - 1.4835
  - 1.4835
  - 1.7453
  - 1.3089
  - 2.2689
  - 2.3561
  - 2.3561

qDotLimLower:
  - -1.4835
  - -1.4835
  - -1.7453
  - -1.3089
  - -2.2689
  - -2.3561
  - -2.3561

# Safety margins to be placed near the joint's positon and velocity limits
qMargin: 0.0
qDotMargin: 0.0
